### ISSUE TITLE
Error when using Python unittest subTests

### ISSUE THREAD

**Issue by paigr** [thought-machine/please#1351]
An `AttributeError` is raised when a `subTest` test case fails, for example:

```python
from unittest import TestCase


class MyTest(TestCase):

    def test_please_subtest(self):
        for i in range(5):
            with self.subTest(i=i):
                self.assertEqual(i % 2, 0)
```

will produce the following when executed by Please:

```
Running tests...
----------------------------------------------------------------------
.
======================================================================
Traceback (most recent call last):
  File "/opt/tm/tools/python/3.7.4-11/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/tm/tools/python/3.7.4-11/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/plz_sandbox/parser_test.pex/__main__.py", line 518, in <module>
  File "/tmp/plz_sandbox/parser_test.pex/__main__.py", line 510, in run
  File "/tmp/plz_sandbox/parser_test.pex/__main__.py", line 351, in interact
  File "/tmp/plz_sandbox/parser_test.pex/__main__.py", line 418, in main
  File "/tmp/plz_sandbox/parser_test.pex/__main__.py", line 493, in run_tests
  File "/tmp/plz_sandbox/parser_test.pex/.bootstrap/xmlrunner/runner.py", line 64, in run
  File "/opt/tm/tools/python/3.7.4-11/usr/lib/python3.7/unittest/runner.py", line 110, in printErrors
    self.printErrorList('FAIL', self.failures)
  File "/tmp/plz_sandbox/parser_test.pex/.bootstrap/xmlrunner/result.py", line 231, in printErrorList
AttributeError: '_SubTest' object has no attribute 'elapsed_time'
```

NOTE: The error does not occur if the test succeeds, only when the test case is marked as failed.

**Comment by Tatskaari** [comment]
Thanks Paulo. Seems like we might need to upgrade the xml report library... We're two major versions behind. Only problem is we host these on get.please.build and I'm in the process of transitioning the hosting over for that. Might be a bit of a delay on this one.
