### ISSUE TITLE
please panics when building targets

### ISSUE THREAD

**Issue by PeterBocan** [thought-machine/please#1750]
When running please in debug mode to debug the following packages I have noticed a panic in the goroutine (not sure what is causing this issue). Please version 16.0.0-rc.4

```
# BUILD
go_binary(
    name = "foo",
    srcs = glob(["*.go"], exclude=["*_test.go"]),
    visibility = ["PUBLIC"],
    deps = [
        "//third_party:xnetcontext",
        "//third_party:xoauth2",
        "//third_party:gdrive-api",
    ],
)

# third_party/BUILD
package(default_visibility=["PUBLIC"])

go_get(
    name = "xnetcontext",
    get = "golang.org/x/net/context",
)

go_get(
    name = "xoauth2",
    get = "golang.org/x/oauth2/...",
    deps = [
        ":ctxhttp",
        ":gcloud-metadata",
    ],
)

go_get(
    name = "ctxhttp",
    get = "golang.org/x/net/context/ctxhttp",
)

go_get(
    name = "gcloud-metadata",
    get = "cloud.google.com/go/compute/metadata",
)

# This takes ages to checkout, this repo is HUUUGE.
# Hence a bit of a black magic from Please build rules.
go_get(
    name = "gdrive-api",
    get = "google.golang.org/api/drive/v3",
    repo = "github.com/googleapis/google-api-go-client/drive/v3", 
)
```

```
00:17:49.801   DEBUG: goroutine 178 [running]:
runtime/debug.Stack(0xd85f20, 0xe064c0, 0xc0002b6f80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/thought-machine/please/src/parse/asp.(*interpreter).interpretStatements.func1(0xc000747a90)
	src/parse/asp/interpreter.go:105 +0x99
panic(0xe064c0, 0xc0002b6f80)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/thought-machine/please/src/parse/asp.(*scope).interpretStatements.func1(0xc0007479d0)
	src/parse/asp/interpreter.go:320 +0xc6
panic(0xe064c0, 0xc0002b6f80)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/thought-machine/please/src/parse/asp.(*scope).interpretExpression.func1(0xc000747690)
	src/parse/asp/interpreter.go:405 +0xbf
panic(0xd5dc20, 0xc000ba4950)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/thought-machine/please/src/fs.(*Globber).Glob(0xc000ac2300, 0xebc4ad, 0x1, 0xc000730170, 0x1, 0x1, 0xc000c86510, 0x3, 0x3, 0x0, ...)
	src/fs/glob.go:101 +0x513
github.com/thought-machine/please/src/parse/asp.glob(0xc0000e6550, 0xc000c864e0, 0x3, 0x3, 0x6, 0x1042fd8)
	src/parse/asp/builtins.go:492 +0x287
github.com/thought-machine/please/src/parse/asp.(*pyFunc).callNative(0xc0004b8380, 0xc0000e6550, 0xc000f02048, 0x1, 0xfffffffa)
	src/parse/asp/objects.go:695 +0x14f
github.com/thought-machine/please/src/parse/asp.(*pyFunc).Call(0xc0004b8380, 0xc0000e6550, 0xc000f02048, 0x0, 0x4)
	src/parse/asp/objects.go:612 +0xd4d
github.com/thought-machine/please/src/parse/asp.(*scope).callObject(0xc0000e6550, 0xc00093c100, 0x4, 0x1041e20, 0xc0004b8380, 0xc000f02048, 0x940271, 0xc000134230)
	src/parse/asp/interpreter.go:730 +0x65
github.com/thought-machine/please/src/parse/asp.(*scope).interpretIdent(0xc0000e6550, 0x1041e20, 0xc0004b8380, 0xc000748100, 0xc0004b8380, 0x4)
	src/parse/asp/interpreter.go:576 +0xea
github.com/thought-machine/please/src/parse/asp.(*scope).interpretValueExpressionPart(0xc0000e6550, 0xc000748080, 0x1043218, 0xc0007300c0)
	src/parse/asp/interpreter.go:496 +0x591
github.com/thought-machine/please/src/parse/asp.(*scope).interpretValueExpression(0xc0000e6550, 0xc000748080, 0x1043218, 0xc0007300c0)
	src/parse/asp/interpreter.go:472 +0x3c
github.com/thought-machine/please/src/parse/asp.(*scope).interpretExpression(0xc0000e6550, 0xc000747690, 0x0, 0x0)
	src/parse/asp/interpreter.go:413 +0x578
github.com/thought-machine/please/src/parse/asp.(*pyFunc).validateType(0xc000550a80, 0xc0000e6550, 0x1, 0xc000747690, 0x0, 0x0)
	src/parse/asp/objects.go:727 +0x68
github.com/thought-machine/please/src/parse/asp.(*pyFunc).Call(0xc000550a80, 0xc0000e6550, 0xc000f02018, 0xc000747858, 0x940271)
	src/parse/asp/objects.go:633 +0x3fd
github.com/thought-machine/please/src/parse/asp.(*scope).callObject(0xc0000e6550, 0xc00093c010, 0x9, 0x1041e20, 0xc000550a80, 0xc000f02018, 0x0, 0x443f6a)
	src/parse/asp/interpreter.go:730 +0x65
github.com/thought-machine/please/src/parse/asp.(*scope).interpretIdentStatement(0xc0000e6550, 0xc000c86090, 0x100c000747a18, 0x7f4107f4db88)
	src/parse/asp/interpreter.go:606 +0x5a5
github.com/thought-machine/please/src/parse/asp.(*scope).interpretStatements(0xc0000e6550, 0xc000010578, 0x1, 0x1, 0x0, 0x0)
	src/parse/asp/interpreter.go:342 +0x1e5
github.com/thought-machine/please/src/parse/asp.(*interpreter).interpretStatements(0xc00010f440, 0xc0000e6550, 0xc000010578, 0x1, 0x1, 0x0, 0x0, 0x102a680, 0xc0002b6f80)
	src/parse/asp/interpreter.go:108 +0x8b
github.com/thought-machine/please/src/parse/asp.(*interpreter).interpretAll(0xc00010f440, 0xc000736000, 0xc000010578, 0x1, 0x1, 0x1, 0x0, 0x0)
	src/parse/asp/interpreter.go:89 +0x211
github.com/thought-machine/please/src/parse/asp.(*Parser).ParseFile(0xc00000f1d0, 0xc000736000, 0xc0000362c0, 0x1f, 0x0, 0x0, 0x0, 0x0)
	src/parse/asp/parser.go:104 +0x11a
github.com/thought-machine/please/src/parse.(*aspParser).ParseFile(0xc000319520, 0xc0002f56c0, 0xc000736000, 0xc0000362c0, 0x1f, 0x1f, 0xc001000100)
	src/parse/init.go:81 +0x5f
github.com/thought-machine/please/src/parse.parsePackage(0xc0002f56c0, 0xc001000100, 0x0, 0xebcb7a, 0x3, 0x0, 0x0, 0x0, 0x0, 0xec275f, ...)
	src/parse/parse_step.go:199 +0x1b1
github.com/thought-machine/please/src/parse.parse(0x6, 0xc0002f56c0, 0xc001000100, 0x0, 0xebcb7a, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	src/parse/parse_step.go:59 +0x212
github.com/thought-machine/please/src/parse.Parse(0x6, 0xc0002f56c0, 0xc001000100, 0x0, 0xebcb7a, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	src/parse/parse_step.go:33 +0xa7
github.com/thought-machine/please/src/plz.doTasks.func1(0x6, 0xc0002f56c0, 0xc001000100, 0x0, 0xebcb7a, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	src/plz/plz.go:85 +0x99
created by github.com/thought-machine/please/src/plz.doTasks
	src/plz/plz.go:84 +0x438

... truncated...

/home/peter/Projects/foo/BUILD:4:12: error: error globbing files with *.go: cannot ReadDirents: cannot Open: open plz-out/tmp/third_party/_gdrive-api#get._build/src/google.golang.org/api/drive/analytics: no such file or directory
    name = "foo",
    srcs = glob(["*.go"], exclude=["*_test.go"]),
```

**Comment by PeterBocan** [comment]
So, looking at the code it seems like this is an intentional behaviour but I will leave the judgement for others.

**Comment by PeterBocan** [comment]
Given this error
```
error: error globbing files with *.go: cannot ReadDirents: cannot Open: open plz-out/tmp/third_party/_gdrive-api#get._build/src/google.golang.org/api/drive/analytics: no such file or directory
```
I have looked into that folder and everything seems to be present :thinking:

**Comment by Tatskaari** [comment]
I think this is a bug with glob in the root directory. Judging from that filepath, t's descending into `plz-out` looking for sources. I think it just needs to always exclude that directory.
