### ISSUE TITLE
bootstrap_pexer fails for python3

### ISSUE THREAD

**Issue by dimpavloff** [thought-machine/please#177]
Using a pre-built `please` binary, building `//third_party/python:...` fails  because of what seems like an issue with the bootstrap_pexer. This also means the bootstrap script fails.

This is on ArchLinux. It looks like a python3-related issue; the `python` and `pip` binaries are aliases for `python3` and `pip3` but there is `python2` and `pip2` available, of course.

Adding `defaultinterpreter = python2` to the `.plzconfig` resolves the issue but is this the right fix?

Here's an excerpt, note the `python $(exe //tools/please_pex:bootstrap_pexer) --compile` . 
```
~/code/git/please $ plz build //third_party/python:... -v9
...
Error building target //third_party/python:_pkg_resources#zip: exit status 1
ENVIRONMENT:
PKG=third_party/python
ARCH=amd64
OS=linux
LANG=en_GB.UTF-8
PATH=/usr/local/bin:/usr/bin:/bin
TMP_DIR=/home/dim/code/git/please/plz-out/tmp/third_party/python/_pkg_resources#zip._build
SRCS=third_party/python/pkg_resources.py
OUTS=.pkg_resources.pex.zip
NAME=_pkg_resources#zip
TOOLS=/home/dim/code/git/please/plz-out/bin/tools/jarcat/jarcat /home/dim/code/git/please/plz-out/bin/tools/please_pex/bootstrap_pexer.pex python
OUT=/home/dim/code/git/please/plz-out/tmp/third_party/python/_pkg_resources#zip._build/.pkg_resources.pex.zip
SRC=third_party/python/pkg_resources.py
python $(exe //tools/please_pex:bootstrap_pexer) --compile && $(exe //tools/jarcat) -d -o ${OUTS} -i .
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dim/code/git/please/plz-out/bin/tools/please_pex/bootstrap_pexer.pex/__main__.py", line 25, in <module>
  File "/home/dim/code/git/please/plz-out/bin/tools/please_pex/bootstrap_pexer.pex/.bootstrap/_pex/pex_bootstrapper.py", line 92, in bootstrap_pex
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/dim/code/git/please/plz-out/bin/tools/please_pex/bootstrap_pexer.pex/.bootstrap/_pex/finders.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/dim/code/git/please/plz-out/bin/tools/please_pex/bootstrap_pexer.pex/.bootstrap/pkg_resources.py", line 1518, in <module>
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
...
```

**Comment by peterebden** [comment]
I think the problem is a combination of Python 3.6 (possibly 3.5 too) and an old setuptools; I have a laptop with python3.4 as the default Python which I've used for testing before, and that's fine. Looks like SourceFileLoader moved, and we have an old version of setuptools which doesn't know about the new location. Hopefully an update will fix it.

I don't want to fix the default interpreter to python2 since it's end-of-lifed; ideally you can build it with whatever the machine's default is (although you need both 2 and 3 to build all the parser engines, and the py3 one doesn't work yet, but bootstrap tries to be smart about what it does with those).
