### ISSUE TITLE
go_test panic when testify has unittest failures

### ISSUE THREAD

**Issue by dimpavloff** [thought-machine/please#185]
When using Go's `testing` lib, `plz test` works as expected. With testify, if there are failing tests, one of the goroutine panics and the below gets shown. The panic results in not executing any additional unit tests.
This uses the https://github.com/dimpavloff/plz-go-test-bug repo.

```
plz test //:mylib_tests -p                                                                                                                                                                [31/1156]
09:24:54.305   ERROR: //:mylib_tests: Tests failed. Stdout: === RUN   TestStdLibWorks
--- FAIL: TestStdLibWorks (0.00s)
=== RUN   TestPanic
--- FAIL: TestPanic (0.00s)
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 6 [running]:
panic(0x632220, 0xc42000c0c0)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420076240)
        /usr/lib/go/src/testing/testing.go:579 +0x25d
panic(0x632220, 0xc42000c0c0)
        /usr/lib/go/src/runtime/panic.go:458 +0x243
github.com/stretchr/testify/assert.CallerInfo(0x0, 0x0, 0x0)
        src/github.com/stretchr/testify/assert/assertions.go:111 +0x676
github.com/stretchr/testify/assert.Fail(0x775420, 0xc420076240, 0x678f40, 0xd, 0x0, 0x0, 0x0, 0xc42001e738)
        src/github.com/stretchr/testify/assert/assertions.go:217 +0x34
github.com/stretchr/testify/assert.FailNow(0x775420, 0xc420076240, 0x678f40, 0xd, 0x0, 0x0, 0x0, 0xc41201cefc)
        src/github.com/stretchr/testify/assert/assertions.go:198 +0x7a
mylib.TestPanic(0xc420076240)
        mylib_test.go:14 +0x67
testing.tRunner(0xc420076240, 0x6971d8)
        /usr/lib/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
        /usr/lib/go/src/testing/testing.go:646 +0x2ec
: Tests failed
Fail: //:mylib_tests   0 passed   0 skipped   2 failed Took 0.0s
```

**Comment by peterebden** [comment]
Looks like a (very subtle) testify bug; they expect to have an absolute path (or at least one parent directory, but `go test` tends to use an absolute path) to the file that called `FailNow`, but in an effort to ensure machine-independent builds we invoke the compile tool with `-trimpath` to strip off everything outside the repo, and they don't get the directory they're expecting. Hence this works as expected in subdirectories, given that #184 is worked around.

I've sent https://github.com/stretchr/testify/pull/402 upstream which fixes it.

**Comment by dimpavloff** [comment]
Thanks for looking into it!
