### ISSUE TITLE
Cannot import recent version python "cryptography" package

### ISSUE THREAD

**Issue by sfirmery** [thought-machine/please#2272]
Recent versions of python "cryptography" package cannot be imported.

It seems that the autogenerated `__init__.py` file in nested folders of "cryptography" makes it non importable.

See the example repository here: https://github.com/sfirmery/please_cryptography_issue

Using cryptography version 36.0.1:

```python
ERROR [0.007s]: test_import (test.CryptographyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/please_cryptography_issue/plz-out/tmp/test._test/run_1/test.pex/test.py", line 8, in test_import
    from cryptography import x509
  File "/please_cryptography_issue/plz-out/tmp/test._test/run_1/test.pex/third_party/python/cryptography/x509/__init__.py", line 6, in <module>
    from cryptography.x509 import certificate_transparency
  File "/please_cryptography_issue/plz-out/tmp/test._test/run_1/test.pex/third_party/python/cryptography/x509/certificate_transparency.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: cannot import name 'x509' from 'cryptography.hazmat.bindings._rust' (/please_cryptography_issue/plz-out/tmp/test._test/run_1/test.pex/third_party/python/cryptography/hazmat/bindings/_rust/__init__.py)
```

Testing with `--shell` and removing the generated `__init__.py` make it works:

```bash
plz test :test --shell

chmod u+w $TEST && zip -d $TEST third_party/python/cryptography/hazmat/bindings/_rust/__init__.py && $TEST

Running tests...
----------------------------------------------------------------------
.
----------------------------------------------------------------------
Ran 1 test in 0.091s

OK
```

Maybe it's related to the already existing `__init__.pyi`, like https://github.com/bazelbuild/rules_python/issues/381?

**Comment by numbsafari** [comment]
You need rustc to be installed and on your path somehow.

**Comment by sfirmery** [comment]
@numbsafari `rustc` is found by `which rustc` at `/usr/bin/rustc` and the `third_party/python/cryptography/hazmat/bindings/_rust.abi3.so` is in the wheel file.
I tried again and got the same result.
