### ISSUE TITLE
`pytest` not working with python 3.10

### ISSUE THREAD

**Issue by samwestmoreland** [thought-machine/please#2570]
With `testrunner = pytest` looks like we get a bunch of errors when running with python 3.10 on the path.

The current workaround is to set `defaultinterpreter = python3.9`

**Comment by samwestmoreland** [comment]
```
<frozen importlib._bootstrap>:914: ImportWarning: ModuleDirImport.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: ModuleDirImport.find_spec() not found; falling back to find_module()
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-5.4.3, py-1.8.1, pluggy-0.13.1
rootdir: /home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1
collected 0 items / 1 error

==================================== ERRORS ====================================
___________ ERROR collecting test/python_rules/pytest/test_runner.py ___________
/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/runner.py:244: in from_call
    result = func()
/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/runner.py:264: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/python.py:446: in collect
    self._inject_setup_module_fixture()
/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/python.py:459: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/python.py:261: in obj
    self._obj = obj = self._getobj()
/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/python.py:443: in _getobj
    return self._importtestmodule()
/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/python.py:511: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/py/_path/local.py:701: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/assertion/rewrite.py:143: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/assertion/rewrite.py:330: in _rewrite_test
    co = compile(tree, fn, "exec", dont_inherit=True)
E   TypeError: required field "lineno" missing from alias
=============================== warnings summary ===============================
pytest_test.pex/.bootstrap/_pytest/junitxml.py:417
  /home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/junitxml.py:417: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in
 pytest 6.0.
  Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.

-- Docs: https://docs.pytest.org/en/latest/warnings.html
- generated xml file: /home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/test.results/results.xml -
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/__main__.py", line 488, in <module>
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/__main__.py", line 472, in run
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/__main__.py", line 429, in main
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/__main__.py", line 463, in run_tests
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/config/__init__.py", line 124, in main
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/hooks.py", line 286, in __call__
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/manager.py", line 93, in _hookexec
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/manager.py", line 84, in <lambda>
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/callers.py", line 208, in _multicall
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/callers.py", line 80, in get_result
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/callers.py", line 187, in _multicall
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/main.py", line 240, in pytest_cmdline_main
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/main.py", line 228, in wrap_session
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/hooks.py", line 286, in __call__
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/manager.py", line 93, in _hookexec
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/manager.py", line 84, in <lambda>
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/callers.py", line 203, in _multicall
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/terminal.py", line 727, in pytest_sessionfinish
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/hooks.py", line 286, in __call__
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/manager.py", line 93, in _hookexec
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/manager.py", line 84, in <lambda>
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/pluggy/callers.py", line 203, in _multicall
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/terminal.py", line 746, in pytest_terminal_summary
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/terminal.py", line 1058, in short_test_summary
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/terminal.py", line 1007, in show_simple
  File "/home/swestmoreland/please_dev/please/plz-out/tmp/test/python_rules/pytest/pytest_test._test/run_1/pytest_test.pex/.bootstrap/_pytest/terminal.py", line 1120, in _get_line_with_reprcrash_message
ModuleNotFoundError: No module named 'wcwidth'
```

**Comment by chrisnovakovic** [comment]
I've got this working - do you want the PR in this repo, https://github.com/please-build/python-rules, or both? (I thought new features were supposed to go in the plugin repos, but then I saw this bug filed here instead of there...)

**Comment by Tatskaari** [comment]
Thanks Chris! We're using the Python plugin in core3 now so we can just fix it there.
