### ISSUE TITLE
Goroutine panics when subincluding the plugin repo.

### ISSUE THREAD

**Issue by PeterBocan** [thought-machine/please#2698]
```
18:56:04.711   DEBUG: Invalid build label: //toolchain/cpp//build_defs:cc:
 goroutine 39 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
github.com/thought-machine/please/src/parse/asp.handleErrors({0x10135c8c0, 0x1400028e080})
	src/parse/asp/interpreter.go:133 +0x78
github.com/thought-machine/please/src/parse/asp.(*interpreter).interpretStatements.func1()
	src/parse/asp/interpreter.go:141 +0x34
panic({0x10135c8c0, 0x1400028e080})
	runtime/panic.go:884 +0x204
github.com/thought-machine/please/src/parse/asp.(*scope).interpretStatements.func1()
	src/parse/asp/interpreter.go:404 +0x94
panic({0x1012aec20, 0x1400089c000})
	runtime/panic.go:884 +0x204
github.com/thought-machine/please/src/core.ParseBuildLabel(...)
	src/core/build_label.go:134
github.com/thought-machine/please/src/parse/asp.(*scope).parseLabelInPackage(0x140005960c0, {0x14000132181, 0x1e}, 0x14000462080)
	src/parse/asp/interpreter.go:253 +0x4ac
github.com/thought-machine/please/src/parse/asp.(*scope).parseLabelInContextPkg(0x14000b17028?, {0x14000132181?, 0x14000b17328?})
	src/parse/asp/interpreter.go:258 +0x5c
github.com/thought-machine/please/src/parse/asp.subinclude(0x140005960c0, {0x140004600b0?, 0x1, 0x14000b17328?})
	src/parse/asp/builtins.go:306 +0xbc
github.com/thought-machine/please/src/parse/asp.(*pyFunc).callNative(0x1400039f500, 0x140005960c0, 0x14000474018)
	src/parse/asp/objects.go:742 +0x4bc
github.com/thought-machine/please/src/parse/asp.(*pyFunc).Call(0x1400039f500, {0x1014103d0?, 0x14000122000?}, 0x140005960c0, 0x14000474018)
	src/parse/asp/objects.go:639 +0x61c
github.com/thought-machine/please/src/parse/asp.(*scope).callObject(0x140005960c0?, {0x1400046c040?, 0xa?}, {0x101412f08?, 0x1400039f500?}, 0x1008f8ea4?)
	src/parse/asp/interpreter.go:832 +0xd4
github.com/thought-machine/please/src/parse/asp.(*scope).interpretIdentStatement(0x140005960c0, 0x1400046a0c0)
	src/parse/asp/interpreter.go:707 +0x318
github.com/thought-machine/please/src/parse/asp.(*scope).interpretStatements(0x140005960c0, {0x14000460090, 0x2, 0xf6000140004600a0?})
	src/parse/asp/interpreter.go:426 +0x104
github.com/thought-machine/please/src/parse/asp.(*interpreter).interpretStatements(0x1013964e0?, 0x1400046a120?, {0x14000460090?, 0x6?, 0x1400012c018?})
	src/parse/asp/interpreter.go:144 +0x68
github.com/thought-machine/please/src/parse/asp.(*interpreter).interpretAll(0x1400022e0a0, 0x14000462080, 0x1400046a000, 0x1400046a030, 0x0, {0x14000460090, 0x2, 0x2})
	src/parse/asp/interpreter.go:120 +0x3b0
github.com/thought-machine/please/src/parse/asp.(*Parser).ParseFile(0x1400012a1f8, 0x6?, 0x10105f5f2?, 0x5?, 0x78?, {0x1400046c000, 0xc})
	src/parse/asp/parser.go:91 +0xbc
github.com/thought-machine/please/src/parse.(*aspParser).ParseFile(0x14000592b60?, 0x16f51f943?, 0x14000494000?, 0x4?, 0xa8?, {0x1400046c000?, 0x101258760?})
	src/parse/init.go:122 +0x24
github.com/thought-machine/please/src/parse.parsePackage(0x140000e6000, {{0x16f51f943, 0x6}, {0x16f51f94a, 0x6}, {0x0, 0x0}}, {{0x0, 0x0}, {0x10106456b, ...}, ...}, ...)
	src/parse/parse_step.go:159 +0x3ec
github.com/thought-machine/please/src/parse.parse(0x14000203520?, 0x140000e6000, {{0x16f51f943, 0x6}, {0x16f51f94a, 0x6}, {0x0, 0x0}}, {{0x0, 0x0}, ...}, ...)
	src/parse/parse_step.go:73 +0x260
github.com/thought-machine/please/src/parse.Parse(0x1?, 0x0?, {{0x16f51f943, 0x6}, {0x16f51f94a, 0x6}, {0x0, 0x0}}, {{0x0, 0x0}, ...}, ...)
	src/parse/parse_step.go:31 +0x78
github.com/thought-machine/please/src/plz.Run.func1.1({{{0x16f51f943, 0x6}, {0x16f51f94a, 0x6}, {0x0, 0x0}}, {{0x0, 0x0}, {0x10106456b, 0x9}, ...}, ...})
	src/plz/plz.go:52 +0x98
created by github.com/thought-machine/please/src/plz.Run.func1
	src/plz/plz.go:51 +0x58
```

**Comment by Tatskaari** [comment]
You shouldn't get that stack trace; Please should catch it and unwind it to an asp trace. The error is your build label is invalid though; you're missing a `/` at the beginning: `///toolchain/cpp//...` not `//toolchain/cpp//...`. Also if you're using a plugin repo, you probably want to use the plugin ID for the subrepo name: `///cc//...`

**Comment by PeterBocan** [comment]
well, it's in the debug logs, so I am not sure if it is expected to be logged or not.

**Comment by peterebden** [comment]
Yup, seems like expected behaviour. It's just there to help us investigate if the asp stack unwinding didn't explain it.
