### ISSUE TITLE
`plz test` does not print test output when there's any logs to stderr

### ISSUE THREAD

**Issue by perpetualjourney** [thought-machine/please#2752]
Example:
```
func foo() {
	log.Error("hello world")
	panic("goodbye world")
}

func TestFoo(t *testing.T) {
	foo()
}
```

Expected behaviour:
* Test fails
* log is printed
* panic is printed with trace
* it is clear that the panic comes from TestFoo

Actual behaviour:
* Test fails
* log is printed

Removing the log line causes the panic to be printed correctly,

**Comment by Tatskaari** [comment]
I don't think that's true? 

```
Fail: //src/foo:foo_test   0 passed   0 skipped   0 failed   1 errored Took 70ms
Error: ReturnValue in foo_test
Test returned nonzero but reported no errors
exit status 2
Standard output:
=== RUN   TestFoo
hello world--- FAIL: TestFoo (0.00s)
panic: goodbye world [recovered]
        panic: goodbye world

goroutine 6 [running]:
testing.tRunner.func1.2({0x503120, 0x5515b8})
        /home/jpoole/please/plz-out/bin/third_party/go/toolchain/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
        /home/jpoole/please/plz-out/bin/third_party/go/toolchain/src/testing/testing.go:1399 +0x39f
panic({0x503120, 0x5515b8})
        /home/jpoole/please/plz-out/bin/third_party/go/toolchain/src/runtime/panic.go:884 +0x212
foo_test_lib.foo(...)
        src/foo/foo_test.go:11
foo_test_lib.TestFoo(0x0?)
        src/foo/foo_test.go:15 +0x4e
testing.tRunner(0xc000007d40, 0x52f0a8)
        /home/jpoole/please/plz-out/bin/third_party/go/toolchain/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        /home/jpoole/please/plz-out/bin/third_party/go/toolchain/src/testing/testing.go:1493 +0x35f

//src/foo:foo_test 1 test run in 67ms; 0 passed, 1 errored
    foo_test  ERROR
1 test target and 1 test run; 0 passed, 1 errored.
Total time: 560ms real, 70ms compute.
Messages:
15:10:45.008   ERROR: //src/foo:foo_test failed: Test returned nonzero but reported no errors
```

Maybe this is something wrong with our specific setup in core3. If you agree, I think we should close the public ticket.
