### ISSUE TITLE
please tool lps panics with InteliJ IDEA

### ISSUE THREAD

**Issue by hnridder** [thought-machine/please#561]
Using
Please 13.4.2
InteliJ 2018.3 with gtache LSP support plugin 1.5.1
init timeout set to 60000ms
please panics with the following error message:

 21:35:17.558  NOTICE: build_langserver: reading on stdin, writing on stdout
panic: Invalid build label: //

goroutine 50 [running]:
github.com/thought-machine/please/src/core.ParseBuildLabel(0xc0007ed93c, 0x2, 0xc0006db0cc, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        src/core/build_label.go:110 +0x148
github.com/thought-machine/please/tools/build_langserver/langserver.isVisible(0xc00054ee80, 0xc0006db0cc, 0x2, 0x2)
        tools/build_langserver/langserver/handler.go:277 +0xd4
github.com/thought-machine/please/tools/build_langserver/langserver.(*diagnosticStore).diagnosticFromBuildLabel(0xc000320c90, 0xc00053e2e0, 0xc000681620, 0xd, 0xc, 0xc, 0xc, 0x19, 0x0)
        tools/build_langserver/langserver/diagnostics.go:323 +0x2dd
github.com/thought-machine/please/tools/build_langserver/langserver.(*diagnosticStore).diagnoseExpression(0xc000320c90, 0xc00053e2e0, 0x0, 0x0, 0x1ad, 0xd, 0xd, 0x0, 0x0, 0x1ba, ...)
        tools/build_langserver/langserver/diagnostics.go:144 +0x188
github.com/thought-machine/please/tools/build_langserver/langserver.(*diagnosticStore).storeDiagnostics.func1(0xbb6800, 0xc0002b4900, 0xc0002b4900, 0x0)
        tools/build_langserver/langserver/diagnostics.go:103 +0x42e
github.com/thought-machine/please/src/parse/asp.WalkAST(0xbb6800, 0xc0002b4900, 0xc000320cc0, 0xbb6800, 0xc0002b4900)
        src/parse/asp/util.go:102 +0x58
github.com/thought-machine/please/src/parse/asp.WalkAST(0xab4720, 0xc0005e0f30, 0xc000320cc0, 0xab4720, 0xc0005e0f30)
        src/parse/asp/util.go:113 +0x11b
github.com/thought-machine/please/src/parse/asp.WalkAST(0xac7220, 0xc000328380, 0xc000320cc0, 0xac7220, 0xc000328380)
        src/parse/asp/util.go:116 +0x223
github.com/thought-machine/please/src/parse/asp.WalkAST(0xb55500, 0xc000328380, 0xc000320cc0, 0xb55500, 0xc000328380)
        src/parse/asp/util.go:123 +0x31c
github.com/thought-machine/please/src/parse/asp.WalkAST(0xab49e0, 0xc0005dca80, 0xc000320cc0, 0xab49e0, 0xc0005dca80)
        src/parse/asp/util.go:113 +0x11b
github.com/thought-machine/please/src/parse/asp.WalkAST(0xbd5640, 0xc0002b3f80, 0xc000320cc0, 0xbd5640, 0xc0002b3f80)
        src/parse/asp/util.go:123 +0x31c
github.com/thought-machine/please/src/parse/asp.WalkAST(0xab4ba0, 0xc0002fe5b0, 0xc000320cc0, 0xab4ba0, 0xc0002fe5b0)
        src/parse/asp/util.go:113 +0x11b
github.com/thought-machine/please/src/parse/asp.WalkAST(0xbb6800, 0xc0002e3a78, 0xc000320cc0, 0xbb6800, 0xc0002e3a78)
        src/parse/asp/util.go:123 +0x31c
github.com/thought-machine/please/src/parse/asp.WalkAST(0xb72800, 0xc0002e3a40, 0xc000320cc0, 0xb72800, 0xc0002e3a40)
        src/parse/asp/util.go:123 +0x31c
github.com/thought-machine/please/src/parse/asp.WalkAST(0xacbe60, 0xc000328200, 0xc000320cc0, 0xacbe60, 0xc000328200)
        src/parse/asp/util.go:116 +0x223
github.com/thought-machine/please/src/parse/asp.WalkAST(0xb3bf60, 0xc000328200, 0xc000320cc0, 0xb3bf60, 0xc000328200)
        src/parse/asp/util.go:123 +0x31c
github.com/thought-machine/please/src/parse/asp.WalkAST(0xab45e0, 0xc0005dc9a0, 0xc000320cc0, 0xab45e0, 0xc0005dc9a0)
        src/parse/asp/util.go:113 +0x11b
github.com/thought-machine/please/src/parse/asp.WalkAST(0xb907e0, 0xc0003281e0, 0xc000320cc0, 0xb907e0, 0xc0003281e0)
        src/parse/asp/util.go:123 +0x31c
github.com/thought-machine/please/src/parse/asp.WalkAST(0xab48e0, 0xc0005dc960, 0xc000320cc0, 0xab48e0, 0xc0005dc960)
        src/parse/asp/util.go:113 +0x11b
github.com/thought-machine/please/src/parse/asp.WalkAST(0xb90720, 0xc0006ec2a0, 0xc000320cc0, 0xb90720, 0xc0006ec2a0)
        src/parse/asp/util.go:123 +0x31c
github.com/thought-machine/please/src/parse/asp.WalkAST(0xab48a0, 0xc0006c2900, 0xc000320cc0, 0xab48a0, 0xc0006c2900)
        src/parse/asp/util.go:113 +0x11b
github.com/thought-machine/please/src/parse/asp.WalkAST(0xbd54c0, 0xc00059ac80, 0xc000320cc0, 0xbd54c0, 0xc00059ac80)
        src/parse/asp/util.go:123 +0x31c
github.com/thought-machine/please/src/parse/asp.WalkAST(0xab4b20, 0xc0006bac80, 0xc000320cc0, 0xab4b20, 0xc0006bac80)
        src/parse/asp/util.go:113 +0x11b
github.com/thought-machine/please/src/parse/asp.WalkAST(0xac7260, 0xc000323d40, 0xc000320cc0, 0xc000323d40, 0x40e078)
        src/parse/asp/util.go:116 +0x223
github.com/thought-machine/please/tools/build_langserver/langserver.(*diagnosticStore).storeDiagnostics(0xc000320c90, 0xc00053e2e0, 0xc00053ce80, 0xf, 0x10)
        tools/build_langserver/langserver/diagnostics.go:111 +0x105
github.com/thought-machine/please/tools/build_langserver/langserver.(*diagnosticsPublisher).diagnose(0xc00000eb20, 0xe35480, 0xc0000240d8, 0xc00053e2e0, 0xc000700000, 0x1295, 0xc0006625a0, 0x1d, 0x0, 0x0, ...)
        tools/build_langserver/langserver/diagnostics.go:87 +0x134
github.com/thought-machine/please/tools/build_langserver/langserver.(*LsHandler).publishDiagnostics(0xc0003ed0a0, 0xc000384480, 0x0, 0x0)
        tools/build_langserver/langserver/diagnostics.go:37 +0x165
github.com/thought-machine/please/tools/build_langserver/langserver.(*LsHandler).handleInit.func1(0xc0003ed0a0)
        tools/build_langserver/langserver/handler.go:144 +0x34
created by github.com/thought-machine/please/tools/build_langserver/langserver.(*LsHandler).handleInit
        tools/build_langserver/langserver/handler.go:142 +0x543
Feb 15, 2019 9:35:21 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint notify
WARNING: Failed to send notification message.
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:126)
        at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:88)
        at com.sun.proxy.$Proxy108.didChangeWatchedFiles(Unknown Source)
        at com.github.gtache.lsp.client.languageserver.requestmanager.SimpleRequestManager.didChangeWatchedFiles(SimpleRequestManager.scala:87)
        at com.github.gtache.lsp.requests.FileEventManager$.$anonfun$changedConfiguration$2(FileEventManager.scala:81)
        at com.github.gtache.lsp.requests.FileEventManager$.$anonfun$changedConfiguration$2$adapted(FileEventManager.scala:79)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
        at com.github.gtache.lsp.requests.FileEventManager$.$anonfun$changedConfiguration$1(FileEventManager.scala:79)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
        ... 14 more

**Comment by hnridder** [comment]
With please 13.4.5 and gtache LSP support plugin 1.5.2 the panic doesn't always occur. However, every change in the source file results in a 'stream closed' error message from the plugin:

Feb 21, 2019 10:50:49 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint notify
WARNING: Failed to send notification message.
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:126)
        at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:88)
        at com.sun.proxy.$Proxy108.didChangeWatchedFiles(Unknown Source)
        at com.github.gtache.lsp.client.languageserver.requestmanager.SimpleRequestManager.didChangeWatchedFiles(SimpleRequestManager.scala:87)

**Comment by agenticarus** [comment]
Thanks - we are planning to improve the reliability of the LSP tool in the coming months.
