### ISSUE TITLE
Can't run cryptography pip library (probably because of .so files)

### ISSUE THREAD

**Issue by AlexPavy** [thought-machine/please#567]
Hi,

To run a python flask server in https locally, we need the library cryptography (https://github.com/pyca/cryptography) defined as : 
```
pip_library(
    name = "cryptography",
    version = "2.1.4",
    deps = [
        ":asn1crypto",
        ":cffi",
        ":idna",
        ":six",
    ],
    zip_safe = False,
)
```
However when I run the server I get the error : 
```Traceback (most recent call last):
  File "/tmp/pex_fzdntmsp/third_party/python/werkzeug/serving.py", line 66, in _get_openssl_crypto_module
    from OpenSSL import crypto
  File "/tmp/pex_fzdntmsp/third_party/python/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/tmp/pex_fzdntmsp/third_party/python/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/tmp/pex_fzdntmsp/third_party/python/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/tmp/pex_fzdntmsp/third_party/python/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/tmp/pex_fzdntmsp/third_party/python/cryptography/x509/extensions.py", line 18, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/tmp/pex_fzdntmsp/third_party/python/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'
```

I suppose there is a problem with finding the .so files.

**Comment by AlexPavy** [comment]
Was fixed by adding, to the cffi library, dependency of cryptography : 
```
post_install_commands = ["mv _cffi_backend.*.so _cffi_backend.so"],
```
