### ISSUE TITLE
Unable to use importlib_metadata pip package

### ISSUE THREAD

**Issue by ascandella** [thought-machine/please#753]
We are evaluating Python build tools and ran into an issue with Please:

`kombu`, a part of `celery`, uses the `importlib_metadata` package (to be part of the standard library in Python 3.8) to determine functionality. The way that Please treats pip dependencies seems to have a bad interaction with this package, such that it can't even be imported. On import (in `__init__.py` in importlib_metadata), it tries to find its own version:

https://gitlab.com/python-devs/importlib_metadata/blob/08a3782fc382d4d2671da66a3bc0e11695d091f1/importlib_metadata/__init__.py#L547

This fails with the following error for an application built with Please:

```
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/importlib_metadata/__init__.py", line 547, in <module>
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/importlib_metadata/__init__.py", line 509, in version
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/importlib_metadata/__init__.py", line 482, in distribution
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/importlib_metadata/__init__.py", line 187, in from_name
importlib_metadata.PackageNotFoundError: importlib_metadata
```
We found that Buck also has this issue, but Bazel and Pants do not.

Repro case:

```
$ cat BUILD.plz
pip_library(
  name = 'importlib_metadata',
  version = '0.23',
  package_name = 'importlib-metadata',
  deps = [':zipp'],
)

pip_library(
  name = 'zipp',
  version = '0.6.0',
  outs = ['zipp.py'],
  deps = [':more_itertools'],
)

pip_library(
  name = 'more_itertools',
  version = '7.2.0',
  package_name = 'more-itertools',
)

python_test(
    name = 'repro_case.py',
    srcs = glob(['*.py']),
    deps = [':importlib_metadata'],
)

$ cat repro_case.py
import importlib_metadata

$ plz test
Error: NoResults in repro_case.py
Test failed with no results
exit status 1
Standard output:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/__main__.py", line 422, in <module>
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/__main__.py", line 414, in run
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/__main__.py", line 255, in interact
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/__main__.py", line 322, in main
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/__main__.py", line 394, in run_tests
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/__main__.py", line 348, in get_suite
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/suite.py", line 24, in __init__
    self.addTests(tests)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/suite.py", line 57, in addTests
    for test in tests:
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/__main__.py", line 347, in <genexpr>
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/__main__.py", line 374, in import_tests
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/repro_case.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/importlib_metadata/__init__.py", line 547, in <module>
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/importlib_metadata/__init__.py", line 509, in version
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/importlib_metadata/__init__.py", line 482, in distribution
  File "/Users/aiden/src/please-importlib-metadata/plz-out/tmp/repro_case.py._test/repro_case.py.pex/importlib_metadata/__init__.py", line 187, in from_name
importlib_metadata.PackageNotFoundError: importlib_metadata

//:repro_case.py 1 test run in 249ms; 0 passed, 1 errored
1 test target and 1 test run in 0s; 0 passed, 1 errored. Total time 290ms.
```

**Comment by peterebden** [comment]
Right, I think I have seen this kind of thing before... I think it needs the `dist-info` directories to be output for each `pip_library` as well. I don't think that's hard as long as their names are predictable (unsure if that is the case or not).

**Comment by ascandella** [comment]
Yes, I think you're right. According to Bazel's rules_python, the path should be predictable (https://github.com/bazelbuild/rules_python/blob/9d68f24659e8ce8b736590ba1e4418af06ec2552/packaging/whl.py#L55)

Here is the output of the `.whl` Bazel creates for importlib_metadata (unzipping the file):

```
./importlib_metadata
./importlib_metadata/__init__.py
./importlib_metadata/_compat.py
./importlib_metadata/tests
./importlib_metadata/tests/test_api.py
./importlib_metadata/tests/test_zip.py
./importlib_metadata/tests/__init__.py
./importlib_metadata/tests/test_main.py
./importlib_metadata/tests/test_integration.py
./importlib_metadata/tests/fixtures.py
./importlib_metadata/tests/data
./importlib_metadata/tests/data/__init__.py
./importlib_metadata/tests/data/example-21.12-py3-none-any.whl
./importlib_metadata/tests/data/example-21.12-py3.6.egg
./importlib_metadata/docs
./importlib_metadata/docs/changelog.rst
./importlib_metadata/docs/__init__.py
./importlib_metadata/docs/using.rst
./importlib_metadata/docs/index.rst
./importlib_metadata/docs/conf.py
./importlib_metadata-0.23.dist-info
./importlib_metadata-0.23.dist-info/WHEEL
./importlib_metadata-0.23.dist-info/LICENSE
./importlib_metadata-0.23.dist-info/top_level.txt
./importlib_metadata-0.23.dist-info/RECORD
./importlib_metadata-0.23.dist-info/METADATA
```

```
$ head importlib_metadata-0.23.dist-info/METADATA
Metadata-Version: 2.1
Name: importlib-metadata
Version: 0.23
Summary: Read metadata from Python packages
Home-page: http://importlib-metadata.readthedocs.io/
Author: Barry Warsaw
Author-email: barry@python.org
License: Apache Software License
Platform: UNKNOWN
Classifier: Development Status :: 3 - Alpha
```

Here is the one Please creates:
```
   creating: importlib_metadata/
  inflating: importlib_metadata/__init__.py
  inflating: importlib_metadata/_compat.py
   creating: importlib_metadata/docs/
  inflating: importlib_metadata/docs/__init__.py
  inflating: importlib_metadata/docs/changelog.rst
  inflating: importlib_metadata/docs/conf.py
  inflating: importlib_metadata/docs/index.rst
  inflating: importlib_metadata/docs/using.rst
   creating: importlib_metadata/tests/
  inflating: importlib_metadata/tests/__init__.py
   creating: importlib_metadata/tests/data/
  inflating: importlib_metadata/tests/data/__init__.py
  inflating: importlib_metadata/tests/data/example-21.12-py3-none-any.whl
  inflating: importlib_metadata/tests/data/example-21.12-py3.6.egg
  inflating: importlib_metadata/tests/fixtures.py
  inflating: importlib_metadata/tests/test_api.py
  inflating: importlib_metadata/tests/test_integration.py
  inflating: importlib_metadata/tests/test_main.py
  inflating: importlib_metadata/tests/test_zip.py
```

So it doesn't have the dist-info directory, which seems to explain this issue. I'll see if I can find some time today to work on a PR to Please to add this support.

**Comment by ascandella** [comment]
I've verified that the following patch fixes the issue with importlib_metadata:

```diff
diff --git i/rules/python_rules.build_defs w/rules/python_rules.build_defs
index 8273c3d8..cbb48217 100644
--- i/rules/python_rules.build_defs
+++ w/rules/python_rules.build_defs
@@ -360,7 +360,8 @@ def pip_library(name:str, version:str, hashes:list=None, package_name:str=None,
             repo_flag = '-f ' + repo

     target = outs[0] if install_subdirectory else '.'
-
+    outs += [f'{name}-{version}.dist-info']
+
     # TODO: This is a total mess on pip's side with --user flag. https://github.com/pypa/pip/issues/1668
     cmd = 'PIP_CONFIG_FILE=/dev/null $TOOLS_PIP install --isolated --no-deps --no-compile --no-cache-dir --default-timeout=60 --target=' + target
     if CONFIG.HOSTOS == 'darwin':
```

**Comment by macripps** [comment]
Closing this issue as #764 should have fixed it, please reopen if you are still having problems.
